export type ProjectImage = {
  src: string;
  width: number;
  height: number;
};

export type Project = {
  slug: string;
  title: string;
  subtitle: string;
  category: "editorials" | "commercial" | "portrait" | "events";
  portraitType?: "artists" | "people";
  year: string;
  client: string;
  location: string;
  description: string;
  cover: ProjectImage;
  images: ProjectImage[];
};

export const projects: Project[] = [
  {
    slug: "dayami-23-59",
    title: "23:59",
    subtitle: "A fashion story with Dayami",
    category: "editorials",
    year: "2025",
    client: "Self-initiated",
    location: "Berlin",
    description:
      "A fashion story set in the last minute before midnight. Sharp silhouettes and restless light trace the tension between elegance and urgency, shot with Dayami across Berlin.",
    cover: { src: "/work/editorial/dayami-23-59/analog-portrait-berlin-fotografin-artist.webp", width: 800, height: 1186 },
    images: [
      { src: "/work/editorial/dayami-23-59/analog-elvira-nisman-fashion-photography-berlin.webp", width: 800, height: 534 },
      { src: "/work/editorial/dayami-23-59/analog-portrait-berlin-fotografin-artist.webp", width: 800, height: 1186 },
      { src: "/work/editorial/dayami-23-59/berlin-photographer-people-elvira-nisman.webp", width: 800, height: 1171 },
      { src: "/work/editorial/dayami-23-59/berlin-portrait-fotografie-elvira-nisman.webp", width: 1100, height: 1630 },
      { src: "/work/editorial/dayami-23-59/elvira-nisman-photography-berlin.webp", width: 800, height: 1188 },
      { src: "/work/editorial/dayami-23-59/fashion-photography-elvira-nisman.webp", width: 700, height: 1020 },
      { src: "/work/editorial/dayami-23-59/photographer-berlin-elvira-nisman.webp", width: 1100, height: 1600 },
      { src: "/work/editorial/dayami-23-59/r1-01816-0002-kopie.webp", width: 1200, height: 1705 },
      { src: "/work/editorial/dayami-23-59/r1-01816-0008-kopie.webp", width: 1563, height: 2000 },
      { src: "/work/editorial/dayami-23-59/r1-01816-0027.webp", width: 1332, height: 2000 },
      { src: "/work/editorial/dayami-23-59/studio-photography-elvira-nisman-berlin.webp", width: 900, height: 659 },
      { src: "/work/editorial/dayami-23-59/berlin-photography-model-editorial.webp", width: 1000, height: 1543 },
      { src: "/work/editorial/dayami-23-59/female-body-photographer-berlin.webp", width: 1100, height: 751 },
      { src: "/work/editorial/dayami-23-59/people-photography-berlin-nisman.webp", width: 1100, height: 1595 },
    ],
  },
  {
    slug: "from-rio-with-love",
    title: "From Rio with Love",
    subtitle: "Bikini shoot",
    category: "commercial",
    year: "2025",
    client: "From Rio with Love",
    location: "Berlin",
    description:
      "Swimwear campaign shot in open light — salt, movement and color straight from Rio.",
    cover: { src: "/work/commercial/from-rio-with-love/dscf8755.webp", width: 1329, height: 2000 },
    images: [
      { src: "/work/commercial/from-rio-with-love/dscf8755.webp", width: 1329, height: 2000 },
      { src: "/work/commercial/from-rio-with-love/dscf8779-copy.webp", width: 1340, height: 2000 },
      { src: "/work/commercial/from-rio-with-love/dscf8863.webp", width: 1333, height: 2000 },
      { src: "/work/commercial/from-rio-with-love/dscf8924.webp", width: 1341, height: 2000 },
      { src: "/work/commercial/from-rio-with-love/dscf8955.webp", width: 2000, height: 1414 },
      { src: "/work/commercial/from-rio-with-love/dscf8958.webp", width: 1333, height: 2000 },
      { src: "/work/commercial/from-rio-with-love/dscf9085.webp", width: 1428, height: 2000 },
      { src: "/work/commercial/from-rio-with-love/dscf9116.webp", width: 2000, height: 1263 },
      { src: "/work/commercial/from-rio-with-love/dscf9142.webp", width: 1333, height: 2000 },
      { src: "/work/commercial/from-rio-with-love/dscf9192.webp", width: 1390, height: 2000 },
      { src: "/work/commercial/from-rio-with-love/dscf9344.webp", width: 1333, height: 2000 },
      { src: "/work/commercial/from-rio-with-love/dscf9357.webp", width: 1413, height: 2000 },
      { src: "/work/commercial/from-rio-with-love/dscf9438.webp", width: 1444, height: 2000 },
      { src: "/work/commercial/from-rio-with-love/dscf9477.webp", width: 1333, height: 2000 },
      { src: "/work/commercial/from-rio-with-love/dscf9597-2.webp", width: 1341, height: 2000 },
      { src: "/work/commercial/from-rio-with-love/dscf9616.webp", width: 1333, height: 2000 },
      { src: "/work/commercial/from-rio-with-love/dscf9754-2.webp", width: 1382, height: 2000 },
      { src: "/work/commercial/from-rio-with-love/dscf9947.webp", width: 2000, height: 1381 },
    ],
  },
  {
    slug: "actor-julia-sedcard",
    title: "Julia",
    subtitle: "Actor sedcard",
    category: "portrait",
    portraitType: "artists",
    year: "2025",
    client: "Julia",
    location: "Berlin",
    description:
      "Sedcard portraits for actor Julia — precise, open and close to the person.",
    cover: { src: "/work/portrait/actor-julia-sedcard/dscf7226-kopie.webp", width: 1389, height: 2000 },
    images: [
      { src: "/work/portrait/actor-julia-sedcard/dscf7226-kopie.webp", width: 1389, height: 2000 },
      { src: "/work/portrait/actor-julia-sedcard/dscf7231-kopie.webp", width: 1336, height: 2000 },
      { src: "/work/portrait/actor-julia-sedcard/dscf7231.webp", width: 1336, height: 2000 },
      { src: "/work/portrait/actor-julia-sedcard/dscf7241.webp", width: 1336, height: 2000 },
      { src: "/work/portrait/actor-julia-sedcard/dscf7241bw-kopie.webp", width: 1445, height: 2000 },
      { src: "/work/portrait/actor-julia-sedcard/dscf7281-kopie.webp", width: 1442, height: 2000 },
      { src: "/work/portrait/actor-julia-sedcard/dscf7286-kopie.webp", width: 1364, height: 2000 },
    ],
  },
  {
    slug: "emily",
    title: "Emily",
    subtitle: "For Roll Up Magazine",
    category: "editorials",
    year: "2025",
    client: "Roll Up Magazine",
    location: "Berlin",
    description:
      "Editorial story with Emily for Roll Up Magazine — analog textures, unhurried light and a quiet kind of confidence.",
    cover: { src: "/work/editorial/emily/000026.webp", width: 1442, height: 2000 },
    images: [
      { src: "/work/editorial/emily/000026.webp", width: 1442, height: 2000 },
      { src: "/work/editorial/emily/000028-kopie.webp", width: 1321, height: 2000 },
      { src: "/work/editorial/emily/000034.webp", width: 1463, height: 2000 },
      { src: "/work/editorial/emily/000039.webp", width: 1609, height: 2000 },
      { src: "/work/editorial/emily/dscf4604.webp", width: 1340, height: 2000 },
      { src: "/work/editorial/emily/dscf4622.webp", width: 1348, height: 2000 },
      { src: "/work/editorial/emily/dscf4717.webp", width: 1333, height: 2000 },
      { src: "/work/editorial/emily/dscf5109.webp", width: 1316, height: 2000 },
      { src: "/work/editorial/emily/dscf5171.webp", width: 1370, height: 2000 },
    ],
  },
  {
    slug: "auna",
    title: "Auna Studio",
    subtitle: "Jewelry campaign",
    category: "commercial",
    year: "2024",
    client: "Auna Studio",
    location: "Berlin",
    description:
      "Campaign photography for Auna Studio. Jewelry treated as sculpture — precise compositions, calm skin tones and a quiet studio light that lets the metal speak.",
    cover: { src: "/work/commercial/auna/berlin-fashion-mode-schmuck-fotograf.webp", width: 1000, height: 1501 },
    images: [
      { src: "/work/commercial/auna/berlin-fashion-mode-schmuck-fotograf.webp", width: 1000, height: 1501 },
      { src: "/work/commercial/auna/berlin-fashion-photographer-elvira-nisman.webp", width: 1500, height: 1871 },
      { src: "/work/commercial/auna/berlin-photographer-kunst-schmuck.webp", width: 1333, height: 2000 },
      { src: "/work/commercial/auna/berlin-photographer-portrait.webp", width: 1407, height: 2000 },
      { src: "/work/commercial/auna/berlin-photography-artist-elvira-nisman.webp", width: 1500, height: 1852 },
      { src: "/work/commercial/auna/headshoots-berlin-mitte-fotograf.webp", width: 1000, height: 1393 },
      { src: "/work/commercial/auna/portrait-berlin-fotograf-people.webp", width: 1333, height: 2000 },
      { src: "/work/commercial/auna/commercial-ecommerce-berlin-photographer.webp", width: 1356, height: 2000 },
      { src: "/work/commercial/auna/portrait-ecommerce-elvira-niman.webp", width: 1440, height: 2000 },
    ],
  },
  {
    slug: "dj-press-kit-nika",
    title: "Nika",
    subtitle: "DJ press kit",
    category: "portrait",
    portraitType: "artists",
    year: "2025",
    client: "Nika",
    location: "Berlin",
    description:
      "Press kit portraits for DJ Nika — grain, blur and night colors that sound like her sets.",
    cover: { src: "/work/portrait/dj-press-kit-nika/dscf3041.webp", width: 1431, height: 2000 },
    images: [
      { src: "/work/portrait/dj-press-kit-nika/dscf3041.webp", width: 1431, height: 2000 },
      { src: "/work/portrait/dj-press-kit-nika/dscf3086.webp", width: 1386, height: 2000 },
      { src: "/work/portrait/dj-press-kit-nika/dscf3172.webp", width: 1364, height: 2000 },
      { src: "/work/portrait/dj-press-kit-nika/dscf3229.webp", width: 1455, height: 2000 },
      { src: "/work/portrait/dj-press-kit-nika/blurryedit2.webp", width: 1351, height: 2000 },
      { src: "/work/portrait/dj-press-kit-nika/edit2-2.webp", width: 1351, height: 2000 },
      { src: "/work/portrait/dj-press-kit-nika/edit3-kopiebnw.webp", width: 1386, height: 2000 },
      { src: "/work/portrait/dj-press-kit-nika/edit5.webp", width: 1445, height: 2000 },
      { src: "/work/portrait/dj-press-kit-nika/edit8.webp", width: 1450, height: 2000 },
      { src: "/work/portrait/dj-press-kit-nika/preview3.webp", width: 1402, height: 2000 },
    ],
  },
  {
    slug: "anya",
    title: "Anya",
    subtitle: "Studio editorial",
    category: "editorials",
    year: "2024",
    client: "Anya Studio",
    location: "Berlin",
    description:
      "Studio editorial with Anya. Clean backdrops, strong poses and a wardrobe that moves between streetwear and tailoring.",
    cover: { src: "/work/editorial/anya/1.webp", width: 1522, height: 2000 },
    images: [
      { src: "/work/editorial/anya/1.webp", width: 1522, height: 2000 },
      { src: "/work/editorial/anya/2.webp", width: 1501, height: 2000 },
      { src: "/work/editorial/anya/3.webp", width: 1341, height: 2000 },
      { src: "/work/editorial/anya/4.webp", width: 1574, height: 2000 },
      { src: "/work/editorial/anya/dscf0324-bearbeitet1.webp", width: 1332, height: 2000 },
      { src: "/work/editorial/anya/dscf0337-2.webp", width: 1485, height: 2000 },
      { src: "/work/editorial/anya/dscf036311-kopie.webp", width: 1397, height: 2000 },
      { src: "/work/editorial/anya/dscf0465.webp", width: 1357, height: 2000 },
      { src: "/work/editorial/anya/dscf0510.webp", width: 1356, height: 2000 },
      { src: "/work/editorial/anya/dscf0545-kopie.webp", width: 1350, height: 2000 },
      { src: "/work/editorial/anya/dscf06661.webp", width: 2000, height: 1465 },
      { src: "/work/editorial/anya/r1-02316-0010.webp", width: 1341, height: 2000 },
      { src: "/work/editorial/anya/r1-03380-0006.webp", width: 1365, height: 2000 },
    ],
  },
  {
    slug: "miah-jewellry",
    title: "MIAH Jewellery",
    subtitle: "Jewelry campaign",
    category: "commercial",
    year: "2025",
    client: "MIAH Jewellery",
    location: "Berlin",
    description:
      "Campaign for MIAH Jewellery — pieces worn, held and lived in rather than displayed.",
    cover: { src: "/work/commercial/miah-jewellry/dscf1313-kopie.webp", width: 1431, height: 2000 },
    images: [
      { src: "/work/commercial/miah-jewellry/dscf1313-kopie.webp", width: 1431, height: 2000 },
      { src: "/work/commercial/miah-jewellry/dscf1369-kopie.webp", width: 1391, height: 2000 },
      { src: "/work/commercial/miah-jewellry/dscf1378-kopie.webp", width: 1649, height: 2000 },
      { src: "/work/commercial/miah-jewellry/dscf1414-kopie.webp", width: 1510, height: 2000 },
      { src: "/work/commercial/miah-jewellry/dscf1541-kopie.webp", width: 1434, height: 2000 },
      { src: "/work/commercial/miah-jewellry/dscf1554-kopie.webp", width: 1424, height: 2000 },
      { src: "/work/commercial/miah-jewellry/dscf1731-kopie.webp", width: 2000, height: 1366 },
      { src: "/work/commercial/miah-jewellry/dscf1757-kopie.webp", width: 1543, height: 2000 },
      { src: "/work/commercial/miah-jewellry/dscf1787-kopie.webp", width: 1511, height: 2000 },
    ],
  },
  {
    slug: "dj-press-kit-maria",
    title: "Maria",
    subtitle: "DJ press kit",
    category: "portrait",
    portraitType: "artists",
    year: "2025",
    client: "Maria",
    location: "Berlin",
    description:
      "Press kit portraits for DJ Maria — hard light, attitude and stillness between sets.",
    cover: { src: "/work/portrait/dj-press-kit-maria/bw.webp", width: 1359, height: 2000 },
    images: [
      { src: "/work/portrait/dj-press-kit-maria/bw.webp", width: 1359, height: 2000 },
      { src: "/work/portrait/dj-press-kit-maria/dscf8151.webp", width: 1377, height: 2000 },
      { src: "/work/portrait/dj-press-kit-maria/dscf8188.webp", width: 1329, height: 2000 },
      { src: "/work/portrait/dj-press-kit-maria/dscf8199.webp", width: 1391, height: 2000 },
      { src: "/work/portrait/dj-press-kit-maria/dscf8252.webp", width: 1336, height: 2000 },
      { src: "/work/portrait/dj-press-kit-maria/dscf8293.webp", width: 1418, height: 2000 },
      { src: "/work/portrait/dj-press-kit-maria/dscf8375.webp", width: 1392, height: 2000 },
      { src: "/work/portrait/dj-press-kit-maria/dscf8409bw.webp", width: 1336, height: 2000 },
    ],
  },
  {
    slug: "anekdot-boutique",
    title: "Anekdot Boutique",
    subtitle: "Brand campaign",
    category: "commercial",
    year: "2025",
    client: "Anekdot Boutique",
    location: "Berlin",
    description:
      "Campaign imagery for Anekdot Boutique — sustainable pieces photographed close to the body, honest and unretouched.",
    cover: { src: "/work/commercial/anekdot-boutique/dscf2018.webp", width: 1392, height: 2000 },
    images: [
      { src: "/work/commercial/anekdot-boutique/2.webp", width: 2000, height: 1403 },
      { src: "/work/commercial/anekdot-boutique/dscf2018.webp", width: 1392, height: 2000 },
      { src: "/work/commercial/anekdot-boutique/dscf2077.webp", width: 2000, height: 1260 },
      { src: "/work/commercial/anekdot-boutique/dscf2093.webp", width: 1530, height: 2000 },
      { src: "/work/commercial/anekdot-boutique/dscf2215.webp", width: 1311, height: 2000 },
      { src: "/work/commercial/anekdot-boutique/dscf2279.webp", width: 1436, height: 2000 },
      { src: "/work/commercial/anekdot-boutique/dscf2287.webp", width: 1685, height: 2000 },
      { src: "/work/commercial/anekdot-boutique/dscf2303.webp", width: 1333, height: 2000 },
      { src: "/work/commercial/anekdot-boutique/dscf2347.webp", width: 1397, height: 2000 },
      { src: "/work/commercial/anekdot-boutique/dscf2355.webp", width: 1418, height: 2000 },
      { src: "/work/commercial/anekdot-boutique/dscf2396.webp", width: 1465, height: 2000 },
      { src: "/work/commercial/anekdot-boutique/dscf2402.webp", width: 1445, height: 2000 },
    ],
  },
  {
    slug: "actor-ruby-sedcard",
    title: "Ruby",
    subtitle: "Actor sedcard",
    category: "portrait",
    portraitType: "artists",
    year: "2024",
    client: "Ruby",
    location: "Berlin",
    description:
      "Sedcard portraits for actor Ruby — black and white, direct and unguarded.",
    cover: { src: "/work/portrait/actor-ruby-sedcard/elvira-nisman-portrait-fotografie-berlin-copy.webp", width: 1435, height: 2000 },
    images: [
      { src: "/work/portrait/actor-ruby-sedcard/elvira-nisman-portrait-fotografie-berlin-copy.webp", width: 1435, height: 2000 },
      { src: "/work/portrait/actor-ruby-sedcard/model-photography-elvira-nisman-berlin.webp", width: 1434, height: 2000 },
      { src: "/work/portrait/actor-ruby-sedcard/portrait-photographer-berlin-actors.webp", width: 1419, height: 2000 },
      { src: "/work/portrait/actor-ruby-sedcard/portraitfotograf-elvira-nisman-berlin.webp", width: 1448, height: 2000 },
      { src: "/work/portrait/actor-ruby-sedcard/schauspieler-portrait-berlin-fotografie.webp", width: 1251, height: 2000 },
      { src: "/work/portrait/actor-ruby-sedcard/black-white-portrait-berlin-kopie.webp", width: 1432, height: 2000 },
    ],
  },
  {
    slug: "unveil-the-night",
    title: "Unveil the Night",
    subtitle: "HTW graduation fashion story",
    category: "editorials",
    year: "2022",
    client: "HTW Berlin",
    location: "Berlin",
    description:
      "A fashion story created as part of an HTW Berlin graduation collection. Fabric, shadow and skin arranged around a single idea: letting the light undress the garment.",
    cover: { src: "/work/editorial/unveil-the-night/dscf3517.webp", width: 1333, height: 2000 },
    images: [
      { src: "/work/editorial/unveil-the-night/dscf3517.webp", width: 1333, height: 2000 },
      { src: "/work/editorial/unveil-the-night/dscf3866.webp", width: 2000, height: 1276 },
      { src: "/work/editorial/unveil-the-night/dscf3898.webp", width: 1333, height: 2000 },
      { src: "/work/editorial/unveil-the-night/dscf3929.webp", width: 1361, height: 2000 },
      { src: "/work/editorial/unveil-the-night/dscf3988-copy-kopie.webp", width: 1300, height: 1892 },
      { src: "/work/editorial/unveil-the-night/dscf3993.webp", width: 1487, height: 2000 },
      { src: "/work/editorial/unveil-the-night/dscf4086.webp", width: 1333, height: 2000 },
      { src: "/work/editorial/unveil-the-night/dscf4104.webp", width: 1368, height: 2000 },
      { src: "/work/editorial/unveil-the-night/dscf4253-kopie.webp", width: 1374, height: 2000 },
      { src: "/work/editorial/unveil-the-night/dscf4318.webp", width: 1333, height: 2000 },
      { src: "/work/editorial/unveil-the-night/dscf4330.webp", width: 1414, height: 2000 },
      { src: "/work/editorial/unveil-the-night/r1-05210-0003.webp", width: 1391, height: 2000 },
      { src: "/work/editorial/unveil-the-night/r1-05210-0007.webp", width: 1331, height: 2000 },
      { src: "/work/editorial/unveil-the-night/r1-05210-0011-copy.webp", width: 1000, height: 1441 },
      { src: "/work/editorial/unveil-the-night/r1-05210-0018.webp", width: 1382, height: 2000 },
    ],
  },
  {
    slug: "laura-stolz",
    title: "Laura Stolz",
    subtitle: "Brand shooting",
    category: "commercial",
    year: "2024",
    client: "Laura Stolz",
    location: "Berlin",
    description:
      "Brand shooting with Laura Stolz — product and person sharing the same calm frame.",
    cover: { src: "/work/commercial/laura-stolz/dscf4065.webp", width: 1349, height: 2000 },
    images: [
      { src: "/work/commercial/laura-stolz/dscf4065.webp", width: 1349, height: 2000 },
      { src: "/work/commercial/laura-stolz/dscf4103.webp", width: 1333, height: 2000 },
      { src: "/work/commercial/laura-stolz/dscf4218.webp", width: 1347, height: 2000 },
      { src: "/work/commercial/laura-stolz/dscf4238.webp", width: 1372, height: 2000 },
      { src: "/work/commercial/laura-stolz/dscf4242.webp", width: 2000, height: 1456 },
      { src: "/work/commercial/laura-stolz/dscf4324.webp", width: 2000, height: 1407 },
      { src: "/work/commercial/laura-stolz/dscf4418.webp", width: 1393, height: 2000 },
      { src: "/work/commercial/laura-stolz/dscf4489.webp", width: 1387, height: 2000 },
      { src: "/work/commercial/laura-stolz/dscf4536.webp", width: 1363, height: 2000 },
      { src: "/work/commercial/laura-stolz/dscf4557.webp", width: 1355, height: 2000 },
    ],
  },
  {
    slug: "calemi-jewelry",
    title: "Calemi Jewelry",
    subtitle: "Jewelry campaign",
    category: "commercial",
    year: "2025",
    client: "Calemi Jewelry",
    location: "Berlin",
    description:
      "Jewelry campaign for Calemi — detail, skin and metal in a slow, deliberate rhythm.",
    cover: { src: "/work/commercial/calemi-jewelry/dscf6598-kopie.webp", width: 1200, height: 1619 },
    images: [
      { src: "/work/commercial/calemi-jewelry/dscf6598-kopie.webp", width: 1200, height: 1619 },
      { src: "/work/commercial/calemi-jewelry/dscf6691-kopie.webp", width: 1336, height: 2000 },
      { src: "/work/commercial/calemi-jewelry/dscf6924bw-kopie.webp", width: 1200, height: 1763 },
      { src: "/work/commercial/calemi-jewelry/dscf7084.webp", width: 1850, height: 2000 },
      { src: "/work/commercial/calemi-jewelry/dscf7102-kopie.webp", width: 1200, height: 1797 },
      { src: "/work/commercial/calemi-jewelry/dscf7114-kopie.webp", width: 1000, height: 1457 },
      { src: "/work/commercial/calemi-jewelry/dscf7149-kopie.webp", width: 1000, height: 686 },
      { src: "/work/commercial/calemi-jewelry/elviranisman-elvira-nisman-berlin-08.webp", width: 1335, height: 2000 },
      { src: "/work/commercial/calemi-jewelry/elviranisman-elvira-nisman-berlin-09-kopie.webp", width: 1365, height: 2000 },
    ],
  },
  {
    slug: "ziehesan-upcycling-brand",
    title: "Ziehesan",
    subtitle: "Upcycling brand lookbook",
    category: "commercial",
    year: "2023",
    client: "Ziehesan",
    location: "Berlin",
    description:
      "Lookbook for upcycling brand Ziehesan. A loose, documentary approach to menswear — honest postures, daylight and the texture of the city between takes.",
    cover: { src: "/work/commercial/ziehesan-upcycling-brand/dscf7449-kopie.webp", width: 1000, height: 1356 },
    images: [
      { src: "/work/commercial/ziehesan-upcycling-brand/dscf7449-kopie.webp", width: 1000, height: 1356 },
      { src: "/work/commercial/ziehesan-upcycling-brand/dscf7460-kopie.webp", width: 1000, height: 1390 },
      { src: "/work/commercial/ziehesan-upcycling-brand/dscf7599-copy-kopie.webp", width: 1200, height: 1856 },
      { src: "/work/commercial/ziehesan-upcycling-brand/dscf7619-kopie.webp", width: 1200, height: 1575 },
      { src: "/work/commercial/ziehesan-upcycling-brand/dscf7794-kopie.webp", width: 1200, height: 1647 },
      { src: "/work/commercial/ziehesan-upcycling-brand/dscf7806-kopie.webp", width: 1200, height: 1756 },
      { src: "/work/commercial/ziehesan-upcycling-brand/dscf7811.webp", width: 1336, height: 2000 },
      { src: "/work/commercial/ziehesan-upcycling-brand/dscf7822.webp", width: 1336, height: 2000 },
      { src: "/work/commercial/ziehesan-upcycling-brand/dscf7857.webp", width: 1336, height: 2000 },
      { src: "/work/commercial/ziehesan-upcycling-brand/dscf7873.webp", width: 1396, height: 2000 },
      { src: "/work/commercial/ziehesan-upcycling-brand/dscf7912-kopie.webp", width: 1200, height: 1797 },
      { src: "/work/commercial/ziehesan-upcycling-brand/dscf7934-kopie.webp", width: 1694, height: 2000 },
      { src: "/work/commercial/ziehesan-upcycling-brand/dscf8083-kopie.webp", width: 1200, height: 1689 },
    ],
  },
];

export const categories = ["editorials", "commercial", "portrait", "events"] as const;

export type Category = (typeof categories)[number];
